# Generated by Django 6.0.4 on 2026-04-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsubmission',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/'),
        ),
    ]
