# Generated by Django 6.0.4 on 2026-04-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0004_kycsubmission_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycsubmission',
            name='business_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='business_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='monthly_volume',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
