# Generated by Django 6.0.4 on 2026-04-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0005_alter_kycsubmission_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsubmission',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
