# Generated by Django 6.0.4 on 2026-04-27 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0006_kycsubmission_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('PAN', 'PAN'), ('AADHAAR', 'Aadhaar'), ('BANK_STATEMENT', 'Bank Statement')], max_length=30),
        ),
        migrations.AlterField(
            model_name='document',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='kyc.kycsubmission'),
        ),
    ]
